Repository vitejs/vite-plugin-react, pull requests merged in 2025-08, with the labels that each got.

#658 fix(rsc): avoid unnecessary server hmr due to tailwind module deps
  packages/plugin-rsc/e2e/basic.test.ts
  packages/plugin-rsc/e2e/fixture.ts
  packages/plugin-rsc/examples/basic/src/framework/entry.browser.tsx
  packages/plugin-rsc/examples/basic/src/routes/tailwind/unused.tsx
  packages/plugin-rsc/examples/basic/src/styles.css
  packages/plugin-rsc/src/plugin.ts
Labels: trigger: preview

#657 feat(rsc): support `client` environment as `react-server`
  packages/plugin-rsc/e2e/browser-mode.test.ts
  packages/plugin-rsc/e2e/helper.ts
  packages/plugin-rsc/e2e/starter.ts
  packages/plugin-rsc/e2e/syntax-error.test.ts
  packages/plugin-rsc/examples/browser-mode/README.md
  packages/plugin-rsc/examples/browser-mode/index.html
  packages/plugin-rsc/examples/browser-mode/package.json
  packages/plugin-rsc/examples/browser-mode/public/vite.svg
  packages/plugin-rsc/examples/browser-mode/src/action-bind/client.tsx
  packages/plugin-rsc/examples/browser-mode/src/action-bind/form.tsx
  packages/plugin-rsc/examples/browser-mode/src/action-bind/server.tsx
  packages/plugin-rsc/examples/browser-mode/src/action-from-client/action.tsx
  packages/plugin-rsc/examples/browser-mode/src/action-from-client/client.tsx
  packages/plugin-rsc/examples/browser-mode/src/action.tsx
  packages/plugin-rsc/examples/browser-mode/src/assets/react.svg
  packages/plugin-rsc/examples/browser-mode/src/client.tsx
  packages/plugin-rsc/examples/browser-mode/src/framework/entry.browser.tsx
  packages/plugin-rsc/examples/browser-mode/src/framework/entry.rsc.tsx
  packages/plugin-rsc/examples/browser-mode/src/framework/main.tsx
  packages/plugin-rsc/examples/browser-mode/src/index.css
  packages/plugin-rsc/examples/browser-mode/src/root.tsx
  packages/plugin-rsc/examples/browser-mode/tsconfig.json
  packages/plugin-rsc/examples/browser-mode/vite.config.ts
  packages/plugin-rsc/package.json
  packages/plugin-rsc/playwright.config.ts
  packages/plugin-rsc/src/plugin.ts
  pnpm-lock.yaml
Labels: trigger: preview

#687 fix(rsc): support cjs on module runner
  packages/plugin-rsc/e2e/basic.test.ts
  packages/plugin-rsc/package.json
  packages/plugin-rsc/src/plugin.ts
  packages/plugin-rsc/src/plugins/cjs.ts
  packages/plugin-rsc/src/plugins/utils.ts
  packages/plugin-rsc/src/transforms/cjs.test.ts
  packages/plugin-rsc/src/transforms/cjs.ts
  pnpm-lock.yaml
Labels: trigger: preview

#705 fix(rsc): warn dual module of optimized and non-optimized client reference
  packages/plugin-rsc/e2e/basic.test.ts
  packages/plugin-rsc/e2e/fixture.ts
  packages/plugin-rsc/src/plugin.ts
Labels: trigger: preview

#716 fix(react): respect `reactRefreshHost` option on rolldown-vite
  packages/plugin-react/CHANGELOG.md
  packages/plugin-react/src/index.ts
Labels: p3-minor-bug 🔨, plugin: react

#721 fix(rsc): keep `import.meta.glob` during scan build for rolldown-vite
  packages/plugin-rsc/examples/basic/src/routes/import-meta-glob/dep.tsx
  packages/plugin-rsc/examples/basic/src/routes/import-meta-glob/server.tsx
  packages/plugin-rsc/examples/basic/src/routes/root.tsx
  packages/plugin-rsc/examples/basic/vite.config.ts
  packages/plugin-rsc/src/plugin.ts
  packages/plugin-rsc/src/plugins/scan.test.ts
  packages/plugin-rsc/src/plugins/scan.ts
Labels: trigger: preview

#768 fix(rsc): fix client reference preload when group chunk re-exports client components from entry chunk
  packages/plugin-rsc/src/plugin.ts
Labels: trigger: preview

#767 feat(rsc): ability to merge client reference chunks based on server chunk usage
  packages/plugin-rsc/e2e/basic.test.ts
  packages/plugin-rsc/examples/basic/vite.config.ts
  packages/plugin-rsc/src/plugin.ts
Labels: trigger: preview

#770 fix(rsc): normalize group chunk virtual id properly
  packages/plugin-rsc/src/plugin.ts
Labels: trigger: preview

#776 fix(rsc): fix CSS HMR with `?url`
  packages/plugin-rsc/e2e/basic.test.ts
  packages/plugin-rsc/examples/basic/src/routes/css-queries/client.tsx
  packages/plugin-rsc/examples/basic/src/routes/style-client/client-url.css
  packages/plugin-rsc/examples/basic/src/routes/style-client/client.tsx
  packages/plugin-rsc/examples/basic/src/routes/style-server/server-url.css
  packages/plugin-rsc/examples/basic/src/routes/style-server/server.tsx
  packages/plugin-rsc/src/plugin.ts
Labels: trigger: preview

#783 perf(react): skip transform hook completely in rolldown-vite in dev if possible
  packages/plugin-react/CHANGELOG.md
  packages/plugin-react/src/index.ts
Labels: plugin: react

#788 fix(rsc): propagate client reference invalidation to server
  packages/plugin-rsc/e2e/basic.test.ts
  packages/plugin-rsc/examples/basic/src/routes/hmr-client-dep/client.tsx
  packages/plugin-rsc/examples/basic/src/routes/hmr-client-dep2/client-dep.ts
  packages/plugin-rsc/examples/basic/src/routes/hmr-client-dep2/client.tsx
  packages/plugin-rsc/examples/basic/src/routes/hmr-client-dep3/client-a.tsx
  packages/plugin-rsc/examples/basic/src/routes/hmr-client-dep3/client-b.tsx
  packages/plugin-rsc/examples/basic/src/routes/hmr-client-dep3/client-dep-comp.tsx
  packages/plugin-rsc/examples/basic/src/routes/hmr-client-dep3/client-dep.ts
  packages/plugin-rsc/examples/basic/src/routes/hmr-client-dep3/server.tsx
  packages/plugin-rsc/examples/basic/src/routes/root.tsx
  packages/plugin-rsc/src/plugin.ts
Labels: trigger: preview

#797 fix(rsc): use `req.originalUrl` for server handler
  packages/plugin-rsc/e2e/base.test.ts
  packages/plugin-rsc/examples/starter/src/framework/entry.rsc.tsx
  packages/plugin-rsc/examples/starter/src/root.tsx
  packages/plugin-rsc/src/plugin.ts
Labels: trigger: preview

#798 perf: remove unnecessary export checks
  packages/common/refresh-runtime.js
Labels: p2-nice-to-have 🍰
