Repository vitejs/vite-plugin-react, pull requests merged in 2025-04, with the labels that each got.

#433 ci: use Node 22 for macOS and Windows CI
  .github/workflows/ci.yml
Labels: p1-chore 🧹

#434 chore: remove npm-run-all2
  package.json
  pnpm-lock.yaml
Labels: p1-chore 🧹

#441 chore: align test setup with core
  playground/ssr-react/vite.config.js
  playground/vitestGlobalSetup.ts
  playground/vitestSetup.ts
Labels: p1-chore 🧹

#442 chore: refactor test setup
  playground/vitest.config.e2e.ts
  playground/vitestSetup.ts
Labels: p1-chore 🧹

#431 chore: align package.json
  .github/workflows/publish.yml
  packages/plugin-react-swc/package.json
  packages/plugin-react-swc/scripts/bundle.ts
  packages/plugin-react/package.json
  scripts/publishCI.ts
  scripts/release.ts
Labels: p1-chore 🧹

#443 refactor: extract common code in common package
  packages/common/index.ts
  packages/common/package.json
  packages/common/refresh-runtime.js
  packages/common/refresh-utils.ts
  packages/common/warning.ts
  packages/plugin-react-swc/package.json
  packages/plugin-react-swc/playground/hmr/__tests__/hmr.spec.ts
  packages/plugin-react-swc/playground/react-18/__tests__/react-18.spec.ts
  packages/plugin-react-swc/scripts/bundle.ts
  packages/plugin-react-swc/src/index.ts
  packages/plugin-react/package.json
  packages/plugin-react/scripts/copyRefreshRuntime.ts
  packages/plugin-react/scripts/copyRefreshUtils.ts
  packages/plugin-react/src/fast-refresh.ts
  packages/plugin-react/src/index.ts
  packages/plugin-react/src/refreshUtils.js
  pnpm-lock.yaml
Labels: p1-chore 🧹

#445 chore: add type field to plugin-react package
  packages/plugin-react/package.json
Labels: p2-nice-to-have 🍰

#446 ci(plugin-swc): bump version number in package.json when release
  packages/plugin-react-swc/package.json
  scripts/release.ts
Labels: p1-chore 🧹

#448 chore: update release-scripts and clean up
  package.json
  packages/plugin-react-swc/package.json
  pnpm-lock.yaml
  scripts/publishCI.ts
Labels: p1-chore 🧹

#420 feat: add `reactRefreshHost` option to support module federation HMR
  packages/common/refresh-utils.ts
  packages/plugin-react-swc/CHANGELOG.md
  packages/plugin-react-swc/README.md
  packages/plugin-react-swc/src/index.ts
  packages/plugin-react/CHANGELOG.md
  packages/plugin-react/README.md
  packages/plugin-react/src/index.ts
Labels: plugin: react, plugin: react-swc

#453 chore: update release action
  .github/workflows/publish.yml
Labels: p1-chore 🧹

#457 chore: ignore react by renovate in compiler-react-18 playground
  .github/renovate.json5
Labels: p1-chore 🧹

#451 feat: add support for rolldown-vite
  packages/plugin-react-swc/CHANGELOG.md
  packages/plugin-react-swc/src/index.ts
  packages/plugin-react/CHANGELOG.md
  packages/plugin-react/src/index.ts
Labels: p3-significant 🔨, plugin: react, plugin: react-swc

#456 chore(deps): update react compiler version
  .github/renovate.json5
  playground/compiler-react-18/package.json
  playground/compiler/package.json
  pnpm-lock.yaml
Labels: dependencies, p1-chore 🧹

#459 test(react): wait for hmr update to reduce flakyness
  playground/react/__tests__/react.spec.ts
Labels: p1-chore 🧹

#468 ci: remove "remove enhancement pending label" step
  .github/workflows/issue-labeled.yml
Labels: p1-chore 🧹

#467 fix(react): inject `__self` and `__source` by babel for rolldown-vite
  packages/plugin-react/src/index.ts
Labels: p3-minor-bug 🔨, plugin: react
