Repository vitejs/vite-plugin-react, pull requests merged in 2025-07, with the labels that each got.

#554 build: use tsdown for plugin-react / plugin-react-oxc
  packages/plugin-react-oxc/build.config.ts
  packages/plugin-react-oxc/package.json
  packages/plugin-react-oxc/scripts/copyRefreshRuntime.ts
  packages/plugin-react-oxc/src/build.d.ts
  packages/plugin-react-oxc/src/index.ts
  packages/plugin-react-oxc/tsconfig.json
  packages/plugin-react-oxc/tsdown.config.ts
  packages/plugin-react/build.config.ts
  packages/plugin-react/package.json
  packages/plugin-react/scripts/copyRefreshRuntime.ts
  packages/plugin-react/src/build.d.ts
  packages/plugin-react/src/index.ts
  packages/plugin-react/tsconfig.json
  packages/plugin-react/tsdown.config.ts
  pnpm-lock.yaml
  scripts/patchCJS.ts
Labels: p1-chore 🧹

#576 fix(rsc): await handler to avoid unhandled rejection
  packages/plugin-rsc/src/plugin.ts
Labels: trigger: preview

#586 fix!: remove `resolve.dedupe`
  packages/plugin-react/CHANGELOG.md
  packages/plugin-react/src/index.ts
Labels: breaking change, plugin: react

#612 feat(rsc): add support for `experimental.renderBuiltUrl` on assets metadata
  packages/plugin-rsc/e2e/fixture.ts
  packages/plugin-rsc/e2e/starter.test.ts
  packages/plugin-rsc/src/plugin.ts
  packages/plugin-rsc/src/ssr.tsx
  packages/plugin-rsc/src/types/virtual.d.ts
Labels: trigger: preview

#626 fix(rsc): handle transform errors before server hmr
  packages/plugin-rsc/e2e/syntax-error.test.ts
  packages/plugin-rsc/src/plugin.ts
  packages/plugin-rsc/src/vite-utils.ts
Labels: trigger: preview

#643 fix(rsc): improve auto css heuristics
  packages/plugin-rsc/e2e/basic.test.ts
  packages/plugin-rsc/examples/basic/package.json
  packages/plugin-rsc/examples/basic/src/routes/root.tsx
  packages/plugin-rsc/examples/basic/test-dep/css-in-server/package.json
  packages/plugin-rsc/examples/basic/test-dep/css-in-server/server.css
  packages/plugin-rsc/examples/basic/test-dep/css-in-server/server.d.ts
  packages/plugin-rsc/examples/basic/test-dep/css-in-server/server.js
  packages/plugin-rsc/src/plugin.ts
  pnpm-lock.yaml
Labels: trigger: preview

#609 feat: merge `plugin-react-oxc` into `plugin-react`
  .github/workflows/ci.yml
  packages/plugin-react-oxc/CHANGELOG.md
  packages/plugin-react-oxc/src/index.ts
  packages/plugin-react-swc/src/index.ts
  packages/plugin-react/CHANGELOG.md
  packages/plugin-react/src/index.ts
  packages/plugin-rsc/e2e/starter.test.ts
  playground/class-components/__tests__/oxc/class-components.spec.ts
  playground/hmr-false/__tests__/oxc/hmr-false.spec.ts
  playground/hook-with-jsx/__tests__/oxc/hook-with-jsx.spec.ts
  playground/mdx/__tests__/oxc/mdx.spec.ts
  playground/react-env/__tests__/oxc/react.spec.ts
  playground/react-sourcemap/__tests__/oxc/react-sourcemap.spec.ts
  playground/react/__tests__/oxc/react.spec.ts
  playground/ssr-react/__tests__/oxc/ssr-react.spec.ts
  playground/vitest.config.e2e.ts
  playground/vitestGlobalSetup.ts
  playground/vitestSetup.ts
Labels: plugin: react, plugin: react-oxc

#649 fix(react): use development jsx transform for `NODE_ENV=development` build
  packages/plugin-react/CHANGELOG.md
  packages/plugin-react/src/index.ts
  packages/plugin-rsc/e2e/starter.test.ts
  playground/tsconfig.json
Labels: p3-minor-bug 🔨, plugin: react
